fix: Creation of an Intance with a Capacity Reservation ID
terraform-aws-modules/terraform-aws-ec2-instance pull request #278
Opened 2022-07-19 15:54 UTC by schniber

## Description
When trying to call the module with the specification of a Capacity Reservation ID, the module ends up with the following error:

╷
│ Error: Invalid function argument
│
│ on .terraform/modules/terraform-aws-ec2-instance/main.tf line 45, in resource "aws_instance" "this":
│ 45: capacity_reservation_id = lookup(capacity_reservation_target.value, "capacity_reservation_id", null)
│ ├────────────────
│ │ capacity_reservation_target.value is "cr-xxxxxxxx"
│
│ Invalid value for "inputMap" parameter: lookup() requires a map as the
│ first argument.
╵

As per line 45 analysis, it looks like the bug is in the following statement:

capacity_reservation_id = lookup(capacity_reservation_target.value, "capacity_reservation_id", null)

it should rather be as follows:

capacity_reservation_id = lookup(capacity_reservation_target, "capacity_reservation_id", null)

In this case, terraform should lookup in the capacity reservation target map (since it is the iterator in the for_each) rather than in its value for the mapping of the attribute capacity reservation id

## Motivation and Context
Fixes #277 

## Breaking Changes
No breaking changes, just fixing a typo in line 45 in the main.tf

## How Has This Been Tested?
- [X] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects
This fix is hard to test since it requires to have an ongoing capacity reservation which is released by AWS.
In order to test this, I stopped at the plan stage.
- [ ] I have executed `pre-commit run -a` on my pull request

2022-07-20 18:02 UTC, schniber commented
Hello @bryantbiggs,

Would it be possible for your to review this PR ?

Thanks in advance.

Bests.

Keep up the good work !

2022-07-21 12:58 UTC, bryantbiggs requested changes
We shouldn't be deleting the README documentation - not sure why our checks are still passing with all this being deleted. Please update when you get a chance

2022-07-21 13:39 UTC, schniber commented
@bryantbiggs  thanks for your feedback.

this was due to the fact that I mistakenly removed the end of tfdocs hook in the complete example README:
<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->

Now pre-commit hooks run correctly.

2022-07-21 14:21 UTC, bryantbiggs commented on examples/complete/main.tf
> +      capacity_reservation_id = "cr-00000000000000000"
we should use an actual reservation here so its deployable - you can see how we do that here https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/examples/complete/main.tf#L468-L472

and you can add a cap reservation resource like https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/examples/complete/main.tf#L796-L802

2022-07-21 15:41 UTC, bryantbiggs commented on examples/complete/main.tf
> +  instance_type               = "m6i.2xlarge"
```suggestion
  instance_type               = "t3.micro"
```

2022-07-21 15:52 UTC, bryantbiggs approved these changes
Thank you @schniber !

2022-07-21 15:52 UTC, merged

2022-07-21 15:53 UTC, antonbabenko commented
This PR is included in version 4.1.1 :tada: